  1. What is data structure and why are they important?

  Ans-Data structure play a pivotal role in computer science and programming, as they are essential for storing, organising, and manipulating data efficiently.

  2.  Explain the difference between mutable and immutable data types with examples.

  Ans- Mutable data types:
These data types can be modified after they are created. For example, in Python, lists, dictionaries, and sets are mutable data types.
Immutable data types:
These data types cannot be changed after they are created. For example, in Python, strings, tuples, integers, and floats are immutable data types.

  3.  What are the main differences between lists and tuples in Python?
   
   Ans-Tuples are similar to list but they are immutable and lists are mutable.

  4. Describe how dictionaries store data.

  Ans- Dictionaries are a data structure in python that store data as key-value pairs.

  5. Why might you use a set instead of a list in Python?

  Ans- Because sets cannot have multiple occurrences of the same element, it makes sets highly useful to efficiently remove duplicate values from a list or tuple and to perform common math operations like unions and intersections.

  6. What is a string in Python, and how is it different from a list?

  Ans- A string is a sequence of characters between single or double quotes. A list is a sequence of items, where each item could be anything (an integer, a float, a string, etc).

  7. How do tuples ensure data integrity in Python?

  Ans-Tuples are immutable to ensure that their contents remain constant throughout their lifecycle, guaranteeing data integrity and reliability.

  8.  What is a hash table, and how does it relate to dictionaries in Python?

  Ans-  A hash table is a data structure that's implemented by the dictionary data type (dict). A dictionary is a type of associative array, also known as a hash table or map.

  9. Can lists contain different data types in Python?

  Ans-  A list  contain a mix of Python types including strings, floats, and booleans.

  10. Explain why strings are immutable in Python.

  Ans- In Python, strings are made immutable so that programmers cannot alter the contents of the object (even by mistake). This avoids unnecessary bugs.

  11.  What advantages do dictionaries offer over lists for certain tasks?

  Ans-A list can store any data type. In contrast, keys in the dictionary can be of any immutable data type, and values can be of any data type. Lists perform faster for ordered operations like sorting, while dictionaries perform faster for lookup operations.

  12. Describe a scenario where using a tuple would be preferable over a list.
  
  Ans-Tuples can't be changed after they're created, but lists can be modified. Tuples use less memory than lists. They are also a bit faster, especially when you're just looking up values. So, if you have data that you don't want to change, it's better to use tuples instead of lists.
  
  13. How do sets handle duplicate values in Python?

  Ans-Sets remove the duplicate value.

  14. How does the “in” keyword work differently for lists and dictionaries?

  Ans- "in" keyword is used to check weather the item is availble in list or not and in dictionary it wors differently.

  15. Can you modify the elements of a tuple? Explain why or why not?

  Ans- No we cannot modify the elements of a tuple because they are immutable.

  16. What is a nested dictionary, and give an example of its use case?

  Ans-A nested dictionary is a dictionary that contains other dictionaries. It's a data structure that's useful for representing data with multiple levels of organization.
Example use cases
Employee records: Organize employees by department, with each employee's details in a nested dictionary.


 17. Describe the time complexity of accessing elements in a dictionary.

 Ans- The time complexity of accessing an element in a Python dictionary is \(O(1)\) on average, but can be \(O(n)\) in the worst case.


  18. what situations are lists preferred over dictionaries?

  Ans-For quick data look-ups, configurations, or caches, favor dictionaries. For ordered collections and sequence operations, such as maintaining a stack or queue, lists are more suitable.


  19. Why are dictionaries considered unordered, and how does that affect data retrieval?

  Ans-A dictionary is termed an unordered collection of objects because dictionaries do not maintain any inherent order of the items based on when they were added.

  20. Explain the difference between a list and a dictionary in terms of data retrieval.

  Ans- A list is an ordered collection of items, whereas a dictionary is an unordered data collection in a key: value pair. Elements from the list can be accessed using the index, while the elements of the dictionary can be accessed using keys.

In [1]:
# Write a code to create a string with your name and print it.

name="Neha"
print(name)

Neha

In [2]:
#Write a code to find the length of the string "Hello World"
len("Hello World")

11

In [3]:
#Write a code to slice the first 3 characters from the string "Python Programming"
s="Python Programming"
s[0:3]

'Pyt'

In [4]:
#Write a code to convert the string "hello" to uppercase.
s="hello"
s.upper()

'HELLO'

In [5]:
# Write a code to replace the word "apple" with "orange" in the string "I like apple"
s="I like apple"
s.replace("apple","orange")

'I like orange'

In [7]:
#Write a code to create a list with numbers 1 to 5 and print it.
l=[1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]

In [8]:
#Write a code to append the number 10 to the list [1, 2, 3, 4]
l=[1,2,3,4]
l.append(10)
print(l)

[1, 2, 3, 4, 10]

In [9]:
#Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]
l=[1,2,3,4,5]
l.remove(3)
print(l)

[1, 2, 4, 5]

In [32]:
#Write a code to access the second element in the list ['a', 'b', 'c', 'd']
list = ['a', 'b', 'c', 'd']
list[1]

'b'

In [14]:
#  Write a code to reverse the list [10, 20, 30, 40, 50].
L=[10, 20, 30, 40, 50]
L.reverse()
print(L)

[50, 40, 30, 20, 10]

In [15]:
#  Write a code to create a tuple with the elements 10, 20, 30 and print it.
t=(10,20,30)
print(t)

(10, 20, 30)

In [31]:
# Write a code to access the first element of the tuple ('apple', 'banana', 'cherry').
t=('apple', 'banana', 'cherry')
t[0]

'apple'

In [24]:
# Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2).
t=(1, 2, 3, 2, 4, 2)
t.count(2)

3

In [25]:
#Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit')
t=('dog', 'cat', 'rabbit')
t.index('cat')

1

In [26]:
#Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').
t=('apple', 'orange', 'banana')
"banana" in t

True

In [27]:
#Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.
set={1,2,3,4,5}
print(set)

{1, 2, 3, 4, 5}

In [28]:
#Write a code to add the element 6 to the set {1, 2, 3, 4}.
s={1,2,3,4}
s.add(6)
print(s)

{1, 2, 3, 4, 6}

In [29]:
#. Write a code to create a tuple with the elements 10, 20, 30 and print it.
t=(10,20,30)
print(t)

(10, 20, 30)

In [30]:
# Write a code to access the first element of the tuple ('apple', 'banana', 'cherry')
t=('apple', 'banana', 'cherry')
t[0]

'apple'

In [34]:
# Write a code to count how many times the number 2 appears in the tuple (1, 2, 3, 2, 4, 2)
t=(1, 2, 3, 2, 4, 2)
t.count(2)

3

In [35]:
#Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').
t=('dog', 'cat', 'rabbit')
t.index('cat')

1

In [36]:
# Write a code to check if the element "banana" is in the tuple ('apple', 'orange', 'banana').
t=('apple', 'orange', 'banana')
"banana" in t

True

In [37]:
# Write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.
set={1,2,3,4,5}
print(set)

{1, 2, 3, 4, 5}

In [38]:
#Write a code to add the element 6 to the set {1, 2, 3, 4}.
set={1,2,3,4}
s.add(6)
print(s)

{1, 2, 3, 4, 6}